image: gitpod/workspace-postgres
  # file: .gitpod.dockerfile

# tasks:
#   - init: npm install
#     command: echo 'start script'
tasks:
  - init: npm install
    command: npm run dev
  - command: pg_start

ports:
  - port: 3000
    onOpen: open-preview
  - port: 5432
    onOpen: notify
